apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qfieldcloud-static-pvc
  namespace: qfieldcloud
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qfieldcloud-media-pvc
  namespace: qfieldcloud
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qfieldcloud-transformation-grids-pvc
  namespace: qfieldcloud
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 5Gi
